### ISSUE TITLE
Collections cannot be listed

### ISSUE THREAD

**Issue by matteocontrini** [grennis/MongoExplorer#2]
Hi,
I have an user on my database with the `dbOwner` role. When I try to connect with your app I get this error:

```
Failed to Get Names
com.mongodb.MongoException: not authorized for query on tracking.system.namespaces
```

What's wrong with the `dbOwner` role? I've been able to successfully use that account on other MongoDB clients.

Thanks

**Comment by maksim77** [comment]
**+1** for this questions

**Comment by grennis** [comment]
I've been trying to update the authentication mechanism from the deprecated call that Mongo Explorer currently uses, however, it seems to fail on Android. I've opened an issue on their jira but it seems like I'm stuck here. Check branch "mongo-java-driver-v3" which is using the new java driver and API but throws some runtime exceptions trying to access SASL classes which don't exist on Android. Jira issue is here:  https://jira.mongodb.org/browse/JAVA-2026

**Comment by matteocontrini** [comment]
Thanks for the update!

**Comment by grennis** [comment]
Update going out on google play now, it works with MongoLab. Had to fork the mongo driver, used latest release 3.1.0, but will require some maintenance to keep it current until mongo provides proper android support.

**Comment by matteocontrini** [comment]
Great. I'll check it as soon as it goes live here.

**Comment by matteocontrini** [comment]
Working even with my custom installation of MongoDB. Thanks :)
